watch_stylesheet: true
watch_config: true
debug: false

komorebi:
    start_command: "komorebic start"
    stop_command: "komorebic stop"
    reload_command: "komorebic stop && komorebic start"

bars:
    status-bar:
        enabled: true
        screens: ["1"]
        class_name: "yasb-bar"
        alignment:
            position: "top"
            center: false
        blur_effect:
            enabled: false
            acrylic: false
            dark_mode: false
            round_corners: true
            border_color: None
        window_flags:
            always_on_top: false
            windows_app_bar: true
        dimensions:
            width: "100%"
            height: 28
        padding:
            top: 0
            left: 0
            bottom: 0
            right: 0
        widgets:
            left: ["weather", "active_window", "komorebi_workspaces"]
            center: ["clock"]
            right: ["language", "media", "volume", "power_menu"]
widgets:
    media:
        type: "yasb.media.MediaWidget"
        options:
            label: "{artist} - {title}"
            label_alt: "<span>\uf001</span> {artist} - {title}"
            hide_empty: true
            max_field_size:
                label: 20
            show_thumbnail: true
            controls_only: false
            controls_left: true
            thumbnail_alpha: 50
            thumbnail_padding: 70
            thumbnail_corner_radius: 12
            icons:
                prev_track: "\ue892"
                next_track: "\ue893"
                play: "\ue768"
                pause: "\ue769"
            callbacks:
                on_left: "do_nothing"

    clock:
        type: "yasb.clock.ClockWidget"
        options:
            label: "<span>\uf017</span> {%d/%m/%Y, %H:%M:%S}"
            label_alt: "<span>\uf017</span> {%a, %d %b %H:%M:%S}"
            timezones: [] #Looking up time zone info from registry
            callbacks:
                on_left: "do_nothing"
    taskbar:
        type: "yasb.taskbar.TaskbarWidget"
        options:
            icon_size: 16
            animation: true
            ignore_apps:
                processes: []
                titles: []
                classes: []
            container_padding:
                top: 0
                left: 8
                bottom: 0
                right: 8
    komorebi_workspaces:
        type: "komorebi.workspaces.WorkspaceWidget"
        options:
            label_offline: "\u26a1 Offline"
            label_workspace_btn: "\udb81\udc3d"
            label_workspace_active_btn: "\udb81\udc3e"
            label_workspace_populated_btn: "\udb81\udc3e"
            label_default_name: "{index}"
            label_zero_index: true
            hide_empty_workspaces: true
            hide_if_offline: true
            animation: true
            container_padding:
                top: 0
                left: 0
                bottom: 0
                right: 0
    komorebi_active_layout:
        type: "komorebi.active_layout.ActiveLayoutWidget"
        options:
            hide_if_offline: true
            label: "{icon}"
            layouts:
                [
                    "bsp",
                    "columns",
                    "rows",
                    "grid",
                    "vertical_stack",
                    "horizontal_stack",
                    "ultrawide_vertical_stack",
                    "right_main_vertical_stack",
                ]
            layout_icons:
                bsp: "BSP"
                columns: "COLS"
                rows: "ROWS"
                grid: "GRID"
                vertical_stack: "V-STACK"
                horizontal_stack: "H-STACK"
                ultrawide_vertical_stack: "W-STACK"
                right_main_vertical_stack: "RMV-STACK"
                monocle: "MONOCLE"
                maximised: "MAX"
                floating: "FLOATING"
                paused: "PAUSED"
            callbacks:
                on_left: "next_layout"
                on_middle: "toggle_monocle"
                on_right: "prev_layout"
            container_padding:
                top: 0
                left: 0
                bottom: 0
                right: 0
    weather:
        type: "yasb.weather.WeatherWidget"
        options:
            label: "<span>{icon}</span> {conditions} {temp} ({min_temp};{max_temp}), {precip}"
            label_alt: "<span>{icon}</span> {conditions} {temp} ({min_temp};{max_temp}), {precip}"
            api_key: "3bf4cf9a7c3f40d6b31174128242807"
            update_interval: 600
            units: "metric"
            hide_decimal: true
            location: "Poland Wroclaw"
            callbacks:
                on_left: "do_nothing"
            icons:
                sunnyDay: "\ue30d"
                clearNight: "\ue32b"
                cloudyDay: "\udb81\udd99"
                cloudyNight: "\ue311"
                rainyDay: "\udb81\ude7e"
                rainyNight: "\udb81\ude7e"
                snowyIcyDay: "\udb81\udd98"
                snowyIcyNight: "\udb81\udd98"
                blizzard: "\uebaa"
                default: "\uebaa"
    volume:
        type: "yasb.volume.VolumeWidget"
        options:
            label: "<span>{icon}</span> {level}"
            label_alt: "{volume}"
            volume_icons:
                - "\ueee8" # Icon for muted
                - "\uf026" # Icon for 0-10% volume
                - "\uf027" # Icon for 11-30% volume
                - "\uf027" # Icon for 31-60% volume
                - "\uf028" # Icon for 61-100% volume
            callbacks:
                on_right: "exec cmd.exe /c start ms-settings:sound"
    power_menu:
        type: "yasb.power_menu.PowerMenuWidget"
        options:
            label: "\uf011"
            uptime: False
            blur: False
            blur_background: True
            animation_duration: 100 # Milisecond
            button_row: 4 # Number of buttons in row, min 1 max 5
            buttons:
                shutdown: ["\uf011", "Shut Down"]
                restart: ["\uead2", "Restart"]
                signout: ["\udb80\udf43", "Sign out"]
                sleep: ["\u23fe", "Sleep"]
                cancel: ["", "Cancel"]
    custom_button:
        type: "yasb.custom.CustomWidget"
        options:
            label: "<span>\udb80\udf5c</span>"
            label_alt: "<span>\udb80\udf5c</span>"
            class_name: "start-menu"
            callbacks:
                on_left: "exec start_menu"
    active_window:
        type: "yasb.active_window.ActiveWindowWidget"
        options:
            label: "{win[process][name]}"
            label_alt: ""
            label_no_window: ""
            label_icon: true
            label_icon_size: 18
            max_length: 40
            max_length_ellipsis: "..."
            monitor_exclusive: false
            callbacks:
                on_left: "do_nothing"
    battery:
        type: "yasb.battery.BatteryWidget"
        options:
            label: "<span>{icon}</span>{percent}%"
            label_alt: "{icon} {percent}% | time: {time_remaining}"
            charging_options:
                icon_format: "{charging_icon}"
    language:
        type: "yasb.language.LanguageWidget"
        options:
            label: "<span>\uf11c</span> {lang[language_code]}"
            label_alt: "{lang[full_name]}"
            update_interval: 1
            callbacks:
                on_left: "do_nothing"
                on_middle: "do_nothing"
                on_right: "do_nothing"
    memory:
        type: "yasb.memory.MemoryWidget"
        options:
            label: "<span>\uf4bc</span> {virtual_mem_free}/{virtual_mem_total}"
            label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
            update_interval: 5000
            callbacks:
                on_left: "toggle_label"
                on_middle: "do_nothing"
                on_right: "do_nothing"
            memory_thresholds:
                low: 25
                medium: 50
        high: 90
    wallpapers:
        type: "yasb.wallpapers.WallpapersWidget"
        options:
            label: "<span>\udb83\ude09</span>"
            image_path: "C:\\your\\Wallpapers\\path" # Example path to folder with images
            change_automatically: false # Automatically change wallpaper
            update_interval: 60 # If change_automatically is true, update interval in seconds
            gallery:
                enabled: true
                blur: true
                image_width: 200
                image_per_page: 7
                show_buttons: false
                orientation: "portrait"
                image_spacing: 8
                lazy_load: true
                lazy_load_delay: 80
                lazy_load_fadein: 400
                image_corner_radius: 20
                enable_cache: true
    wifi:
        type: "yasb.wifi.WifiWidget"
        options:
            label: "<span>{wifi_icon}</span>"
            label_alt: "{wifi_name}"
            update_interval: 5000
            callbacks:
                on_left: "exec cmd.exe /c start ms-settings:network"
                on_middle: "do_nothing"
                on_right: "toggle_label"
    obs:
        type: "yasb.obs.ObsWidget"
        options:
            connection:
                host: "193.147.0.101"
                port: 4400
                password: "yourstrongpassword:3"
            icons:
                recording: "\ueba7"
                stopped: "\ueba5"
                paused: "\ueba7"
            hide_when_not_recording: true
            blinking_icon: true
    update:
        type: "yasb.update_check.UpdateCheckWidget"
        options:
            winget_update:
                enabled: true
                label: "<span>\uf0ab</span>{count}"
                interval: 180
                exclude: []
            windows_update:
                enabled: false
                label: "<span>\uf0ab</span>{count}"
                interval: 240
                exclude: []
